### ISSUE TITLE
Non visualizzo nulla

### ISSUE THREAD

**Issue by Bobsilvio** [virtualdj/pun_sensor#13]
Ciao ho installato la tua integrazione molto interessante, ho l'ultima versione di HA(premetto che da qualche giorno mi sono affacciato ad HA), ma dopo averlo scaricato da HASSIO, non vedo nessuna impostazione.
Tu dici di andare in "configurazione", ma di preciso dove?

**Comment by virtualdj** [comment]
Se sei sicuro di aver installato l'integrazione (automaticamente con HACS o manualmente creando la cartella come scritto nel file README) devi poi aggiungerla in Home Assistant da **Impostazioni > Dispositivi e servizi**. Lì fai clic su **Aggiungi integrazione** e scegli **Prezzi PUN del mese**. Se non dovesse apparire nell'elenco significa che non hai fatto il lavoro correttamente...

**Comment by Bobsilvio** [comment]
hai ragione, ho saltato la parte di aggiungi integrazione, mi sono affacciato da poco ad HA.
grazie

**Comment by Bobsilvio** [comment]
Sarabbe carino anche avere un dato rispetto al mese scorso/tre mesi. Tipo +1%, ho qualcosa del genere.

**Comment by Bobsilvio** [comment]
aggiungo... inserendo anche manualmente la propria tariffa di spread, in modo da avere il prezzo "personale".

**Comment by virtualdj** [comment]
> Sarabbe carino anche avere un dato rispetto al mese scorso/tre mesi.

Non è possibile farlo, in quanto l'integrazione per definizione non "memorizza" ma espone solo un valore attuale (che nel caso specifico viene aggiornato 1 volta al giorno).
Forse si può fare in Home Assistant associando i valori ad una [statistics card](https://www.home-assistant.io/dashboards/statistics-graph/)?

> aggiungo... inserendo anche manualmente la propria tariffa di spread, in modo da avere il prezzo "personale".

Questo lo puoi fare direttamente tu con un [template sensor](https://www.home-assistant.io/integrations/template/); ad esempio aggiungendo questo nel file `configuration.yaml` (valori inventati):

```yaml
# Template sensors
template:
  - sensor:
      - unique_id: prezzo_attuale_energia
        name: 'Prezzo attuale energia'
        icon: mdi:currency-eur
        unit_of_measurement: '€/kWh'
        state: >
          {{ (1.1 * (states('sensor.pun_prezzo_fascia_corrente')|float(0) + 0.0087 + 0.04 + 0.0227))|round(3) }}
```
