### ISSUE TITLE
integrazione sensore per "vendita" materia energia come prodotto solare/eolico di casa

### ISSUE THREAD

**Issue by melotti892** [virtualdj/pun_sensor#15]
salve
come da titolo
è possibile avere un sensore che calcola il prezzo della materia energia "venduta" (immessa in rete) in quanto eccesso di produzione da pannelli solari (nel mio caso)?
legislativamente parlando nel mio caso so che guadagno la metà di quanto costa al prelievo
so che a seconda del mezzo con cui viene prodotta cambia (penso anche del contratto a questo punto)

**Comment by virtualdj** [comment]
Credo che la risposta sia sempre la stessa... un [template sensor](https://github.com/virtualdj/pun_sensor/issues/13#issuecomment-1696327250).

Nel tuo caso potrebbe essere qualcosa del genere:

```yaml
# Template sensors
template:
  - sensor:
      - unique_id: prezzo_energia_venduta
        name: 'Prezzo energia venduta'
        icon: mdi:currency-eur
        unit_of_measurement: '€/kWh'
        state: >
          {{ (0.5 * (states('sensor.pun_prezzo_fascia_corrente')|float(0)))|round(3) }}
```
