### ISSUE TITLE
Cambio tra le fasce orarie non avviene

### ISSUE THREAD

**Issue by TommasoPino** [virtualdj/pun_sensor#16]
Buongiorno, uso il tuo componente da qualche giorno e volevo prima di tutto ringraziarti per l'ottimo lavoro. 

Riscontro però un problema sull'aggiornamento della fascia oraria tra le varie Fx. A volte il sistema manca di cambiare fascia con conseguente sballo dei prezzi generali. Sembra che il sistema usato di schedula non funzioni a dovere. Hai per caso riscontrato lo stesso problema?

Grazie mille e buona giornata

**Comment by virtualdj** [comment]
> A volte il sistema manca di cambiare fascia con conseguente sballo dei prezzi generali. Sembra che il sistema usato di schedula non funzioni a dovere. Hai per caso riscontrato lo stesso problema?

No, sinceramente il cambio di fascia mi sembra funzionare sempre correttamente (anche perché è un mero calcolo che non dipende da API o dati online, quindi estremamente leggero sulla CPU).

Qui uno screenshot appena fatto, puoi controllare col tuo se è diverso.

![Schermata Home Assistant](https://github.com/virtualdj/pun_sensor/assets/3251704/a2dd03ba-b7c4-4f3b-849e-bd695bcc8952)

**Comment by TommasoPino** [comment]
Confermo che è diverso



Il giorno gio 21 set 2023 alle 13:21 virtualdj ***@***.***>
ha scritto:

**Comment by TommasoPino** [comment]
Confermo che è diverso

![image](https://github.com/virtualdj/pun_sensor/assets/22640696/aff4e79f-175b-4545-9898-b87f61eabd9a)

**Comment by virtualdj** [comment]
Prova ad abilitare i log per l'estensione aggiungendo queste voci a `configuration.yaml`:
```yaml
logger:
  default: warning
  logs:
    custom_components.pun_sensor: debug
```
In questa maniera nel log di Home Assistant dovrebbero essere stampate informazioni in merito.
La riga di tuo interesse è quella che inizia con il messaggio `Nuova fascia corrente:`.

Magari è dovuto alla time-zone del sistema dove esegui Home Assistant? Non credo, mi sembrava di averlo testato in una VM con TZ inglese, ma non si sa mai... sto imparando anch'io 😄

**Comment by virtualdj** [comment]
Ho riprovato in una VM ed effettivamente il calcolo delle fasce segue il fuso orario impostato in Home Assistant.

Perciò, se per esempio ho impostato la timezone di Santiago (GMT-3) e in Italia sono le 21:05 (F2), in realtà la fascia verrà identificata con l'ora di Santiago (16:05 a causa dell'ora legale) quindi F1. Dopodiché il prossimo aggiornamento verrà impostato per la fascia F2 (transizione F1 > F2) alle ore 19, ma per Santiago sono 3 ore (16 > 19) mentre in Italia sarebbero 2 (21 > 23) quindi questo sballa tutto!

Evidentemente non avevo considerato questo problema durante lo sviluppo; credo sia opportuno impostare la **timezone fissa sull'ora dell'Italia** per quanto riguarda il calcolo delle fasce orarie, tanto comunque queste sono tipiche italiane, giusto?

**Comment by TommasoPino** [comment]
![image](https://github.com/virtualdj/pun_sensor/assets/22640696/6bd0d1a6-e3aa-4547-9f9d-24812b5e4504)

il problema è che non è che non avvenga all'orario spaccato (sto in italia con il fuso di Roma) ma che avviene ad orari random (il cambio alle 14:06 è dovuto al riavvio schedulato di HA)

Io ho un'altra entità per le fasce orarie che cambio con un select per mezzo di una automazione che funziona perfettamente (non tengo conto del festivo al di fuori della domenica ma è un problema marginale)

```yaml
# configuration.yaml
utility_meter:
   rete_montly_energy:
     source: sensor.generale_casa_energy
     cycle: monthly
     tariffs:
       - F1
       - F2
       - F3
   casa_monthly_energy:
     source: sensor.energia_domestica
     cycle: monthly
     tariffs:
       - F1
       - F2
       - F3
```

```yaml
# automation.yaml
- id: '1670751116400'
  alias: Tariffe energetiche
  description: ''
  trigger:
  - platform: time
    id: '7'
    at: '7:00:00'
    variables:
      tariff: F2
  - platform: time
    id: '8'
    at: '8:00:00'
    variables:
      tariff: F1
  - platform: time
    id: '19'
    at: '19:00:00'
    variables:
      tariff: F2
  - platform: time
    id: '23'
    at: '23:00:00'
    variables:
      tariff: F3
  condition: []
  action:
  - choose:
    - conditions:
      - condition: trigger
        id: '7'
      sequence:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
      - service: select.select_option
        target:
          entity_id: select.rete_montly_energy
        data:
          option: '{{ tariff }}'
      - service: select.select_option
        target:
          entity_id: select.casa_monthly_energy
        data:
          option: '{{ tariff }}'
    - conditions:
      - condition: trigger
        id: '8'
      sequence:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - service: select.select_option
        data:
          option: '{{ tariff }}'
        target:
          entity_id: select.rete_montly_energy
      - service: select.select_option
        data:
          option: '{{ tariff }}'
        target:
          entity_id: select.casa_monthly_energy
    - conditions:
      - condition: trigger
        id: '19'
      sequence:
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
      - service: select.select_option
        target:
          entity_id: select.rete_montly_energy
        data:
          option: '{{ tariff }}'
      - service: select.select_option
        target:
          entity_id: select.casa_monthly_energy
        data:
          option: '{{ tariff }}'
    - conditions:
      - condition: trigger
        id: '23'
      sequence:
      - service: select.select_option
        target:
          entity_id: select.rete_montly_energy
        data:
          option: '{{ tariff }}'
      - service: select.select_option
        target:
          entity_id: select.casa_monthly_energy
        data:
          option: '{{ tariff }}'
  mode: single
  initial_state: true
```
