### ISSUE TITLE
Fascia 23

### ISSUE THREAD

**Issue by Raptor1964S** [virtualdj/pun_sensor#32]
C'è la possibilità di configurare, per chi ha la fascia 23, il PUN fascia F23  come "Prezzo fascia Corrente" ? Grazie

**Comment by virtualdj** [comment]
Al momento no, appena ho qualche idea e soprattutto tempo libero pensavo di introdurre una sorta di configurazione nell'integrazione per scegliere se uno usa la monoraria, la fascia bioraria (F1 e F23) o la trioraria (F1, F2, F3).
Ma siccome tocca riscrivere gran parte del codice al momento non riesco...

Nel frattempo puoi usare un template sensor come questo da inserire in `configuration.yaml`:
```yaml
# Prezzo fascia bioraria corrente
template:
  - sensor:
      - unique_id: prezzo_fascia_bioraria_corrente
        name: 'Prezzo fascia bioraria corrente'
        icon: mdi:currency-eur
        unit_of_measurement: '€/kWh'
        state: >
          {% if states('sensor.pun_fascia_corrente')=='F1' %}{{ states('sensor.pun_fascia_f1')}}{% else %}{{ states('sensor.pun_fascia_f23')}}{% endif %}
```
